
-- 如果只有一个blob/clob字段, 默认情况下不会生成 ModelWithBLOBs

CREATE TABLE t_blob_auto_increment (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(20),
  blob blob,
  clob clob,
  create_time datetime NOT NULL,
  update_time datetime DEFAULT NULL,
  PRIMARY KEY (id)
);
comment on table t_blob_auto_increment is '测试';

comment on column t_blob_auto_increment.id is 'id';
comment on column t_blob_auto_increment.name is '名称';
comment on column t_blob_auto_increment.blob is '二进制';
comment on column t_blob_auto_increment.clob is 'clob';
comment on column t_blob_auto_increment.create_time is '创建时间';
comment on column t_blob_auto_increment.update_time is '创建时间';

