
-- pojo
CREATE TABLE t_table1 (
  id integer NOT NULL,
  title varchar(20) NOT NULL,
  description varchar(1000),
  audit_status varchar(20) unique,
  user_id integer,
  is_deleted bit(1),
  created_date datetime NOT NULL,
  updated_date datetime DEFAULT NULL,
  PRIMARY KEY (id)
);
comment on table t_table1 is '测试1';
comment on column t_table1.id is '主键';
comment on column t_table1.audit_status is '审核状态 {enum: UNAUDITED(待审核), AUDIT_PASS(审核通过), AUDIT_NOT_PASS(审核未通过)}';
comment on column t_table1.title is '标题';
comment on column t_table1.description is '描述';
comment on column t_table1.user_id is '所有者';
comment on column t_table1.is_deleted is '删除状态';
comment on column t_table1.created_date is '创建时间';
comment on column t_table1.updated_date is '创建时间';

-- blob 自增主键
CREATE TABLE t_blob_auto_id (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(20),
  blob blob,
  clob clob,
  created_date datetime NOT NULL,
  updated_date datetime DEFAULT NULL,
  PRIMARY KEY (id)
);
comment on table t_blob_auto_id is '测试';
comment on column t_blob_auto_id.id is '自增主键';
comment on column t_blob_auto_id.name is '名称';
comment on column t_blob_auto_id.blob is '二进制';
comment on column t_blob_auto_id.clob is 'clob';
comment on column t_blob_auto_id.created_date is '创建时间';
comment on column t_blob_auto_id.updated_date is '创建时间';

-- 联合主键
CREATE TABLE t_blob_union_key (
  id integer NOT NULL,
  id2 integer NOT NULL,
  name varchar(20),
  blob blob,
  clob clob,
  is_deleted bit(1),
  created_date datetime NOT NULL,
  PRIMARY KEY (id, id2)
);
comment on table t_blob_union_key is '测试';
comment on column t_blob_union_key.id is '主键1';
comment on column t_blob_union_key.id2 is '主键2';
comment on column t_blob_union_key.name is '名称';
comment on column t_blob_union_key.blob is '二进制';
comment on column t_blob_union_key.clob is 'clob';
comment on column t_blob_union_key.is_deleted is '删除状态';
comment on column t_blob_union_key.created_date is '创建时间';

