-- 自增主键
CREATE TABLE t_blob_auto_increment (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(20),
  blob blob,
  clob clob,
  create_time datetime NOT NULL,
  update_time datetime DEFAULT NULL,
  PRIMARY KEY (id)
);
comment on table t_blob_auto_increment is '测试';

comment on column t_blob_auto_increment.id is '自增主键';
comment on column t_blob_auto_increment.name is '名称';
comment on column t_blob_auto_increment.blob is '二进制';
comment on column t_blob_auto_increment.clob is 'clob';
comment on column t_blob_auto_increment.create_time is '创建时间';
comment on column t_blob_auto_increment.update_time is '创建时间';

-- 联合主键
CREATE TABLE t_blob_union_key (
  id integer NOT NULL,
  id2 integer NOT NULL,
  name varchar(20),
  blob blob,
  clob clob,
  create_time datetime NOT NULL,
  update_time datetime DEFAULT NULL,
  PRIMARY KEY (id, id2)
);
comment on table t_blob_union_key is '测试';

comment on column t_blob_union_key.id is '主键1';
comment on column t_blob_union_key.id2 is '主键2';
comment on column t_blob_union_key.name is '名称';
comment on column t_blob_union_key.blob is '二进制';
comment on column t_blob_union_key.clob is 'clob';
comment on column t_blob_union_key.create_time is '创建时间';
comment on column t_blob_union_key.update_time is '创建时间';

