
-- pojo
create table t_table1 (
  id integer not null,
  gmt_create datetime not null,
  gmt_modified datetime default null,
  is_deleted bit(1),
  audit_status varchar(20) unique,
  user_id integer,
  title varchar(20) not null,
  description varchar(1000),
  primary key (id)
);
comment on table t_table1 is '测试1';
comment on column t_table1.id is '主键';
comment on column t_table1.gmt_create is '创建时间';
comment on column t_table1.gmt_modified is '创建时间';
comment on column t_table1.is_deleted is '删除状态';
comment on column t_table1.audit_status is '审核状态 {enum: UNAUDITED(待审核), AUDIT_PASS(审核通过), AUDIT_NOT_PASS(审核未通过)}';
comment on column t_table1.user_id is '所有者';
comment on column t_table1.title is '标题';
comment on column t_table1.description is '描述';

-- blob 自增主键
create table t_blob_auto_id (
  id integer not null generated by default as identity,
  gmt_create datetime not null,
  gmt_modified datetime default null,
  name varchar(20),
  blob blob,
  clob clob,
  primary key (id)
);
comment on table t_blob_auto_id is '测试';
comment on column t_blob_auto_id.id is '自增主键';
comment on column t_blob_auto_id.gmt_create is '创建时间';
comment on column t_blob_auto_id.gmt_modified is '创建时间';
comment on column t_blob_auto_id.name is '名称';
comment on column t_blob_auto_id.blob is '二进制';
comment on column t_blob_auto_id.clob is 'clob';

-- 联合主键
create table t_blob_union_key (
  id integer not null,
  id2 integer not null,
  gmt_create datetime not null,
  is_deleted bit(1),
  name varchar(20),
  blob blob,
  clob clob,
  primary key (id, id2)
);
comment on table t_blob_union_key is '测试';
comment on column t_blob_union_key.id is '主键1';
comment on column t_blob_union_key.id2 is '主键2';
comment on column t_blob_union_key.gmt_create is '创建时间';
comment on column t_blob_union_key.is_deleted is '删除状态';
comment on column t_blob_union_key.name is '名称';
comment on column t_blob_union_key.blob is '二进制';
comment on column t_blob_union_key.clob is 'clob';

